# Generated by Django 2.1.5 on 2019-01-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email',
            field=models.EmailField(default='something@me.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(default='you@me.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='flights_from',
            field=models.CharField(choices=[('flight_1', '1 flight'), ('flight_2', '2 flights'), ('flight_3', '3 flights'), ('flight_4', '4 flights'), ('flight_5', '5+ flights')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flights_to',
            field=models.CharField(choices=[('flight_1', '1 flight'), ('flight_2', '2 flights'), ('flight_3', '3 flights'), ('flight_4', '4 flights'), ('flight_5', '5+ flights')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='from_property',
            field=models.CharField(choices=[('prop1', 'Apartment/Condo'), ('prop2', 'House'), ('prop3', 'Office/Retail'), ('prop3', 'Storage')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='from_zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='other',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='referral',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reff_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='to_zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='truck_size',
            field=models.IntegerField(help_text='ft'),
        ),
    ]
