# Generated by Django 2.1.5 on 2019-01-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_contact_insurance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Comment',
        ),
    ]
