# Generated by Django 2.1.5 on 2019-03-04 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190206_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flights_from',
            field=models.CharField(choices=[('', 'Flights of Stairs '), ('flight_1', '1 flight or less'), ('flight_2', '2 flights'), ('flight_3', '3 flights'), ('flight_4', '4 flights'), ('flight_5', '5+ flights')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flights_to',
            field=models.CharField(choices=[('', 'Flights of Stairs '), ('flight_1', '1 flight or less'), ('flight_2', '2 flights'), ('flight_3', '3 flights'), ('flight_4', '4 flights'), ('flight_5', '5+ flights')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='from_property',
            field=models.CharField(choices=[('', 'Property Type'), ('prop1', 'Apartment/Condo'), ('prop2', 'House'), ('prop3', 'Office/Retail'), ('prop4', 'Storage')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='insurance',
            field=models.CharField(choices=[('', 'Need Insurance ?'), ('n', 'No'), ('y', 'Yes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='referral',
            field=models.CharField(blank=True, choices=[('', 'Referral Type'), ('ref_1', 'Friend'), ('ref_2', 'Social Media'), ('ref_3', 'Uhaul / MovingHelp'), ('ref_4', 'SML / Penske'), ('ref_5', 'ABF'), ('ref_6', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='truck_size',
            field=models.CharField(max_length=2),
        ),
    ]
